name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Publish app to Google App Engine
      # You may pin to the exact commit or the version.
      # uses: zxyle/publish-gae-action@647a5e5538829de31fdfaad8de523573c417139f
      uses: zxyle/publish-gae-action@v2.3.0
      with:
        # The service account email which will be used for authentication.
        service_account_email: danilo@graziano.digital
        # The service account key which will be used for authentication.
        service_account_key: 102179839364246122584
        # GAE project id
        project_id: gothic-avenue-319909
        # GAE variables to be written to the app.yaml file
       # gae_variables: # optional
        # Path to the app.yml, Defaults to ./app.yml
        #gae_config_path: # optional
      
