name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
           
    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: danilo@graziano.digital
        service_account_key: 102179839364246122584
        project_id: gothic-avenue-319909
        # An optional variables parameter can be used
        #gae_variables: ${{ secrets.GAE_VARIABLES }}

    - name: Publish app to Google App Engine
      run: |
        # This client-secret.json is converted by GCP_SA_KEY.
        gcloud auth activate-service-account gothic-avenue-319909@appspot.gserviceaccount.com --key-file=gothic-avenue-319909-1f0f50c52768.json
        gcloud config set project gothic-avenue-319909
        gcloud -q app deploy app.yaml --promote

        # Suppose you need a cron task.
        #gcloud -q app deploy cron.yaml
        sudo apt-get install google-cloud-sdk-app-engine-go

      
