name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
          
    - name: Setup Google Cloud SDK
        # You may pin to the exact commit or the version.
        # uses: mathieu-bour/setup-gcloud@3bb09468aad23fb31bd9e873e87a189d845063c3
        uses: mathieu-bour/setup-gcloud@1.3.1
        with:
          # Google Cloud SDK to use. If left empty, will use the latest one. On Ubuntu runners, "local" allow to use the pre-installed version of gcloud.
          version: # optional, default is latest
          # The service account key to use, base64-encoded.
          service-account-key: 102179839364246122584# optional
          # The default Google Cloud project. You can change it later.
          project: # optional, default is auto
          # Install additional components (e.g. beta, gsutil, etc.)
          components: # optional
          # Configure Docker to interact with Google Cloud Container Registry. Use true for all repositories, or specify comma-separated registries.
          configure-docker: # optional, default is false
      
